<?php

return array(
    'header_login_screen' => 'Sign in',
    'message_validate_email' => 'Invalid e-mail (e.g. %s)',
    'label_email' => 'E-mail address',
    'label_password' => 'Password',
    'header_join_screen' => 'Join us',
    'label_username' => 'Your nickname',
    'message_validate_username' => 'Only latin characters, digits and no spaces, please',
    'header_forgot_password_screen' => 'Forgot your password?',
    'message_forgot_password' => 'Enter your email address or username, and we will send you an email with instructions for resetting your password.',
    'header_change_password_screen' => 'Change your password',
    'label_old_pass' => 'Old password',
    'label_new_pass' => 'New password',
    'label_once_again' => 'once again',
    'header_logout_screen' => 'Sign out',
    'message_want_to_sign_out' => 'Are you sure you want to sign out?',
    'button_login' => 'Sign in',
    'button_join' => 'Join',
    'button_send_code' => 'Send code',
    'button_reset_password' => 'Reset password',
    'button_change_password' => 'Change password',
    'button_logout' => 'Sign out',
    'button_cancel' => 'Cancel',
    'link_forgot_password' => 'Forgot password?',
    'link_login' => 'Sign in',
    'link_join' => 'Join us',
    'link_change_password' => 'Change password',
    
);
