<?php //echo $this->render('header.phtml'); ?>

<h1>Смена пароля на <?php echo $_SERVER['SERVER_NAME'];?>!</h1>

<div>
    На сайт <a href="http://<?php echo $_SERVER['SERVER_NAME'];?>"><?php echo $_SERVER['SERVER_NAME'];?></a>
    поступил запрос на смену пароля для учетной записи <strong><?php echo $this->user->getLogin();?></strong>
</div>
<div>
    Если запрос сделан по ошибке, либо вы не отправляли
запрос, ничего не делайте и не обращайте внимания на это сообщение.
</div>
<div>
    Чтобы изменить пароль перейдите по <a href="http://<?php echo $_SERVER['SERVER_NAME'].'?activationkey='.$this->activationKey.'&login=' . rawurlencode($this->user->getLogin());?>">ссылке</a> 
</div>

<?php //echo $this->render('footer.phtml'); ?>